[functions]
  external_node_modules = ["express"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/"
  status = 200
  to = "/api/v1/person:splat"
[build]
  functions = "netlify/functions"